// src/constants/locations.ts
// Auto-generated from sorsogon_barangays.csv — do not edit manually
// 15 municipalities, 541 barangays — Sorsogon Province, Philippines

export const MUNICIPALITIES: string[] = [
  'Barcelona',
  'Bulan',
  'Bulusan',
  'Casiguran',
  'Castilla',
  'Donsol',
  'Gubat',
  'Irosin',
  'Juban',
  'Magallanes',
  'Matnog',
  'Pilar',
  'Prieto Diaz',
  'Sorsogon City',
  'Sta. Magdalena',
];

export const BARANGAYS_BY_MUNICIPALITY: Record<string, string[]> = {
  Barcelona: [
    'Alegria',
    'Bagacay',
    'Bangate',
    'Bugtong',
    'Cagang',
    'Fabrica',
    'Jibong',
    'Lago',
    'Layog',
    'Luneta',
    'Macabari',
    'Mapapac',
    'Olandia',
    'Paghaluban',
    'Poblacion Central',
    'Poblacion Norte',
    'Poblacion Sur',
    'Putiao',
    'San Antonio',
    'San Isidro',
    'San Ramon',
    'San Vicente',
    'Santa Cruz',
    'Santa Lourdes',
    'Tagdon',
  ],
  Bulan: [
    'A. Bonifacio',
    'Abad Santos',
    'Aguinaldo',
    'Antipolo',
    'Beguin',
    'Benigno S. Aquino',
    'Bical',
    'Bonga',
    'Butag',
    'Cadandanan',
    'Calomagon',
    'Calpi',
    'Cocok-Cabitan',
    'Daganas',
    'Danao',
    'Dolos',
    'E. Quirino',
    'Fabrica',
    'G. Del Pilar',
    'Gate',
    'Inararan',
    'J. Gerona',
    'J.P. Laurel',
    'Jamorawon',
    'Lajong',
    'Libertad',
    'M. Roxas',
    'Magsaysay',
    'Managanaga',
    'Marinab',
    'Montecalvario',
    'N. Roque',
    'Namo',
    'Nasuje',
    'Obrero',
    'Osmeña',
    'Otavi',
    'Padre Diaz',
    'Palale',
    'Quezon',
    'R. Gerona',
    'Recto',
    'Sagrada',
    'San Francisco',
    'San Isidro',
    'San Juan Bag-o',
    'San Juan Daan',
    'San Rafael',
    'San Ramon',
    'San Vicente',
    'Santa Remedios',
    'Santa Teresita',
    'Sigad',
    'Somagongsong',
    'Taromata',
    'Zone I Pob.',
    'Zone II Pob.',
    'Zone III Pob.',
    'Zone IV Pob.',
    'Zone V Pob.',
    'Zone VI Pob.',
    'Zone VII Pob.',
    'Zone VIII Pob.',
  ],
  Bulusan: [
    'Bagacay',
    'Central',
    'Cogon',
    'Dancalan',
    'Dapdap',
    'Lalud',
    'Looban',
    'Mabuhay',
    'Madlawon',
    'Poctol',
    'Porog',
    'Sabang',
    'Salvacion',
    'San Antonio',
    'San Bernardo',
    'San Francisco',
    'San Isidro',
    'San Jose',
    'San Rafael',
    'San Roque',
    'San Vicente',
    'Santa Barbara',
    'Sapngan',
    'Tinampo',
  ],
  Casiguran: [
    'Adovis',
    'Boton',
    'Burgos',
    'Casay',
    'Cawit',
    'Central',
    'Cogon',
    'Colambis',
    'Escuala',
    'Inlagadian',
    'Lungib',
    'Mabini',
    'Ponong',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Juan',
    'San Pascual',
    'Santa Cruz',
    'Somal-ot',
    'Tigbao',
    'Timbayog',
    'Tiris',
    'Trece Martirez',
    'Tulay',
  ],
  Castilla: [
    'Amomonting',
    'Bagalayag',
    'Bagong Sirang',
    'Bonga',
    'Buenavista',
    'Burabod',
    'Caburacan',
    'Canjela',
    'Cogon',
    'Cumadcad',
    'Dangcalan',
    'Dinapa',
    'La Union',
    'Libtong',
    'Loreto',
    'Macalaya',
    'Maracabac',
    'Mayon',
    'Maypangi',
    'Milagrosa',
    'Miluya',
    'Monte Carmelo',
    'Oras',
    'Pandan',
    'Poblacion',
    'Quirapi',
    'Saclayan',
    'Salvacion',
    'San Isidro',
    'San Rafael',
    'San Roque',
    'San Vicente',
    'Sogoy',
    'Tomalaytay',
  ],
  Donsol: [
    'Alin',
    'Awai',
    'Banban',
    'Bandi',
    'Banuang Gurang',
    'Baras',
    'Bayawas',
    'Bororan Barangay 1',
    'Cabugao',
    'Central Barangay 2',
    'Cristo',
    'Dancalan',
    'De Vera',
    'Gimagaan',
    'Girawan',
    'Gogon',
    'Gura',
    'Juan Adre',
    'Lourdes',
    'Mabini',
    'Malapoc',
    'Malinao',
    'Market Site Barangay 3',
    'New Maguisa',
    'Ogod',
    'Old Maguisa',
    'Orange',
    'Pangpang',
    'Parina',
    'Pawala',
    'Pinamanaan',
    'Poso Pob.',
    'Punta Waling-Waling Pob.',
    'Rawis',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Rafael',
    'San Ramon',
    'San Vicente',
    'Santa Cruz',
    'Sevilla',
    'Sibago',
    'Suguian',
    'Tagbac',
    'Tinanogan',
    'Tongdol',
    'Tres Marias',
    'Tuba',
    'Tupas',
    'Vinisitahan',
  ],
  Gubat: [
    'Ariman',
    'Bagacay',
    'Balud Del Norte',
    'Balud Del Sur',
    'Benguet',
    'Bentuco',
    'Beriran',
    'Buenavista',
    'Bulacao',
    'Cabigaan',
    'Cabiguhan',
    'Carriedo',
    'Casili',
    'Cogon',
    'Cota Na Daco',
    'Dita',
    'Jupi',
    'Lapinig',
    'Luna-Candol',
    'Manapao',
    'Manook',
    'Naagtan',
    'Nato',
    'Nazareno',
    'Ogao',
    'Paco',
    'Panganiban',
    'Paradijon',
    'Patag',
    'Payawin',
    'Pinontingan',
    'Rizal',
    'San Ignacio',
    'Sangat',
    'Santa Ana',
    'Tabi',
    'Tagaytay',
    'Tigkiw',
    'Tiris',
    'Togawe',
    'Union',
    'Villareal',
  ],
  Irosin: [
    'Bacolod',
    'Bagsangan',
    'Batang',
    'Bolos',
    'Buenavista',
    'Bulawan',
    'Carriedo',
    'Casini',
    'Cawayan',
    'Cogon',
    'Gabao',
    'Gulang-Gulang',
    'Gumapia',
    'Liang',
    'Macawayan',
    'Mapaso',
    'Monbon',
    'Patag',
    'Salvacion',
    'San Agustin',
    'San Isidro',
    'San Juan',
    'San Julian',
    'San Pedro',
    'Santo Domingo',
    'Tabon-Tabon',
    'Tinampo',
    'Tongdol',
  ],
  Juban: [
    'Anog',
    'Aroroy',
    'Bacolod',
    'Binanuahan',
    'Biriran',
    'Buraburan',
    'Calateo',
    'Calmayon',
    'Carohayon',
    'Catanagan',
    'Catanusan',
    'Cogon',
    'Embarcadero',
    'Guruyan',
    'Lajong',
    'Maalo',
    'North Poblacion',
    'Puting Sapa',
    'Rangas',
    'Sablayan',
    'Sipaya',
    'South Poblacion',
    'Taboc',
    'Tinago',
    'Tughan',
  ],
  Magallanes: [
    'Aguada Norte',
    'Aguada Sur',
    'Anibong',
    'Bacalon',
    'Bacolod',
    'Banacud',
    'Behia',
    'Biga',
    'Binisitahan del Norte',
    'Binisitahan del Sur',
    'Biton',
    'Bulala',
    'Busay',
    'Caditaan',
    'Cagbolo',
    'Cagtalaba',
    'Cawit Extension',
    'Cawit Proper',
    'Ginangra',
    'Hubo',
    'Incarizan',
    'Lapinig',
    'Magsaysay',
    'Malbog',
    'Pantalan',
    'Pawik',
    'Pili',
    'Poblacion',
    'Salvacion',
    'Santa Elena',
    'Siuton',
    'Tagas',
    'Tulatula Norte',
    'Tulatula Sur',
  ],
  Matnog: [
    'Balocawe',
    'Banogao',
    'Banuangdaan',
    'Bariis',
    'Bolo',
    'Bon-Ot Big',
    'Bon-Ot Small',
    'Cabagahan',
    'Calayuan',
    'Calintaan',
    'Caloocan',
    'Calpi',
    'Camachiles',
    'Camcaman',
    'Coron-coron',
    'Culasi',
    'Gadgaron',
    'Genablan Occidental',
    'Genablan Oriental',
    'Hidhid',
    'Laboy',
    'Lajong',
    'Mambajog',
    'Manjunlad',
    'Manurabi',
    'Naburacan',
    'Paghuliran',
    'Pangi',
    'Pawa',
    'Poropandan',
    'Santa Isabel',
    'Sinalmacan',
    'Sinang-Atan',
    'Sinibaran',
    'Sisigon',
    'Sua',
    'Sulangan',
    'Tablac',
    'Tabunan',
    'Tugas',
  ],
  Pilar: [
    'Abas',
    'Abucay',
    'Bantayan',
    'Banuyo',
    'Bayasong',
    'Bayawas',
    'Binanuahan',
    'Cabiguan',
    'Cagdongon',
    'Calongay',
    'Calpi',
    'Catamlangan',
    'Comapo-capo',
    'Danlog',
    'Dao',
    'Dapdap',
    'Del Rosario',
    'Esmerada',
    'Esperanza',
    'Ginablan',
    'Guiron',
    'Inang',
    'Inapugan',
    'Leona',
    'Lipason',
    'Lourdes',
    'Lubiano',
    'Lumbang',
    'Lungib',
    'Mabanate',
    'Malbog',
    'Marifosque',
    'Mercedes',
    'Migabod',
    'Naspi',
    'Palanas',
    'Pangpang',
    'Pinagsalog',
    'Pineda',
    'Poctol',
    'Pudo',
    'Putiao',
    'Sacnangan',
    'Salvacion',
    'San Antonio',
    'San Antonio',
    'San Jose',
    'San Rafael',
    'Santa Fe',
  ],
  'Prieto Diaz': [
    'Brillante',
    'Bulawan',
    'Calao',
    'Carayat',
    'Diamante',
    'Gogon',
    'Lupi',
    'Maningcay De Oro',
    'Manlabong',
    'Perlas',
    'Quidolog',
    'Rizal',
    'San Antonio',
    'San Fernando',
    'San Isidro',
    'San Juan',
    'San Rafael',
    'San Ramon',
    'Santa Lourdes',
    'Santo Domingo',
    'Talisayan',
    'Tupaz',
    'Ulag',
  ],
  'Sorsogon City': [
    'Abuyog',
    'Almendras-Cogon',
    'Balete',
    'Balogo',
    'Balogo',
    'Barayong',
    'Basud',
    'Bato',
    'Bibincahan',
    'Bitan-o/Dalipay',
    'Bogña',
    'Bon-Ot',
    'Bucalbucalan',
    'Buenavista',
    'Buenavista',
    'Buhatan',
    'Bulabog',
    'Burabod',
    'Cabarbuhan',
    'Cabid-An',
    'Cambulaga',
    'Capuy',
    'Caricaran',
    'Del Rosario',
    'Gatbo',
    'Gimaloto',
    'Guinlajon',
    'Jamislagan',
    'Macabog',
    'Maricrum',
    'Marinas',
    'Osiao',
    'Pamurayan',
    'Pangpang',
    'Panlayaan',
    'Peñafrancia',
    'Piot',
    'Poblacion',
    'Polvorista',
    'Rawis',
    'Rizal',
    'Salog',
    'Salvacion',
    'Salvacion',
    'Sampaloc',
    'San Isidro',
    'San Isidro',
    'San Juan',
    'San Juan',
    'San Pascual',
    'San Ramon',
    'San Roque',
    'San Vicente',
    'Santa Cruz',
    'Santa Lucia',
    'Santo Domingo',
    'Santo Niño',
    'Sawanga',
    'Sirangan',
    'Sugod',
    'Sulucan',
    'Talisay',
    'Ticol',
    'Tugos',
  ],
  'Sta. Magdalena': [
    'Barangay Poblacion I',
    'Barangay Poblacion II',
    'Barangay Poblacion III',
    'Barangay Poblacion IV',
    'La Esperanza',
    'Peñafrancia',
    'Salvacion',
    'San Antonio',
    'San Bartolome',
    'San Eugenio',
    'San Isidro',
    'San Rafael',
    'San Roque',
    'San Sebastian',
  ],
};
